highlighter: pygments
github: [Repository metadata]


defaults:
    -
        scope: 
            path: ""
            type: "pages"    
        values:
            layout: ""
    
    -
        scope:
            path: "_posts"
            type: "posts"
        values:
            layout: ""
    -
        scope:
            path: "_drafts"
            type: "drafts"
        values:
            layout: ""
        
kramdown:
    input: GFM